import NextAuth, { type NextAuthConfig } from "next-auth";
import Google from "next-auth/providers/google";
import Credentials from "next-auth/providers/credentials";
import { DrizzleAdapter } from "@auth/drizzle-adapter";
import { eq, sql } from "drizzle-orm";
import { db } from "@/lib/db/client";
import { users, accounts, sessions, verificationTokens } from "@/lib/db/schema";
import { getEnv } from "@/lib/env";
import { log, metric } from "@/lib/logging/logger";

/**
 * Auth.js v5 with our own canonical users table (decision D1).
 * users.id is generated by us and never changes; providers attach to it.
 *
 * MVP sign-in: Google OAuth. A development-only credentials form exists so the
 * product can be run and tested with no external identity provider; it is
 * refused in production by lib/env.
 */
function buildConfig(): NextAuthConfig {
  const env = getEnv();
  const providers: NextAuthConfig["providers"] = [];

  if (env.AUTH_GOOGLE_ID && env.AUTH_GOOGLE_SECRET) {
    providers.push(
      Google({
        clientId: env.AUTH_GOOGLE_ID,
        clientSecret: env.AUTH_GOOGLE_SECRET,
        allowDangerousEmailAccountLinking: false,
      }),
    );
  }

  if (env.AUTH_DEV_LOGIN && env.NODE_ENV !== "production") {
    providers.push(
      Credentials({
        id: "dev-login",
        name: "Development login",
        credentials: { email: { label: "Email", type: "email" }, name: { label: "Name", type: "text" } },
        async authorize(credentials) {
          const email = String(credentials?.email ?? "").trim().toLowerCase();
          const name = String(credentials?.name ?? "").trim() || null;
          if (!email || !email.includes("@")) return null;
          const existing = await db().query.users.findFirst({ where: sql`lower(${users.email}) = ${email}` });
          if (existing) {
            if (existing.deletedAt) return null;
            return { id: existing.id, email: existing.email, name: existing.name };
          }
          const [created] = await db().insert(users).values({ email, name, emailVerified: new Date() }).returning();
          return { id: created.id, email: created.email, name: created.name };
        },
      }),
    );
  }

  return {
    adapter: DrizzleAdapter(db(), {
      usersTable: users,
      accountsTable: accounts,
      sessionsTable: sessions,
      verificationTokensTable: verificationTokens,
    }),
    providers,
    session: { strategy: "jwt", maxAge: 60 * 60 * 24 * 7 },
    pages: { signIn: "/login" },
    trustHost: true,
    secret: env.AUTH_SECRET,
    callbacks: {
      async jwt({ token, user }) {
        // Only ever carry the immutable users.id. Email is not an identity claim.
        if (user?.id) token.sub = user.id;
        return token;
      },
      async session({ session, token }) {
        if (token.sub) session.user.id = token.sub;
        return session;
      },
      async signIn({ user }) {
        if (!user?.id) return true;
        const row = await db().query.users.findFirst({ where: eq(users.id, user.id) });
        if (row?.deletedAt) {
          metric("auth_failure", { reason: "deleted_user" });
          return false;
        }
        return true;
      },
    },
    events: {
      async signIn({ user, account }) {
        log.info("auth.sign_in", { userId: user.id, provider: account?.provider });
      },
    },
    logger: {
      error(error) {
        metric("auth_failure", { error: error.message });
      },
    },
  };
}

export const { handlers, auth, signIn, signOut } = NextAuth(buildConfig);
